[package]
name = "axelar-monitor"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
base64 = "0.22.1"
cosmos-sdk-proto = { version = "0.27.0", default-features = false, features = [] }
hex = "0.4"
log = "0.4.28"
prost = "0.13"
prost-types = "0.13"
protobuf = "3.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "5.0.0"
tiny_http = "0.12"
toml = "0.8"
ureq = "3.1.2"

[build-dependencies]
prost-build = "0.13"
